packages:
  - openclaw-core
  - openclaw-core/ui
  - openclaw-core/packages/*
  - openclaw-core/extensions/*
  - axtrizenFrontEnd

onlyBuiltDependencies:
  - "@lydell/node-pty"
  - "@matrix-org/matrix-sdk-crypto-nodejs"
  - "@napi-rs/canvas"
  - "@whiskeysockets/baileys"
  - authenticate-pam
  - esbuild
  - node-llama-cpp
  - protobufjs
  - sharp
